version: '3.1'

services:
  mysql:
    image: mysql
    container_name: mysql_netology
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - $HOME/mysql_data:/var/lib/mysql
